# Dev setup helpers (run interactively)
usethis::use_roxygen_md()
usethis::use_testthat()
usethis::use_mit_license("Joshua Uhalt")
usethis::use_readme_rmd(open = FALSE)
usethis::use_vignette("overview")
usethis::use_package("lavaan")
usethis::use_package("semTools")
usethis::use_package("psych")
usethis::use_package("semPlot")
usethis::use_package("dplyr")
usethis::use_package("purrr")
usethis::use_package("tibble")
usethis::use_package("tidyr")
usethis::use_package("stringr")
usethis::use_package("ggplot2")
usethis::use_package("glue")
usethis::use_package("gt")
